CREATE TABLE
IF NOT EXISTS projects
(
    id integer PRIMARY key generated by DEFAULT as IDENTITY,
    name text not null check
(name <> ''),
    priority  integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);


CREATE TABLE
IF NOT EXISTS tasks
(
    id integer PRIMARY key generated by DEFAULT as IDENTITY,
    name text not null check
(name <> ''),
    done boolean,
    projectid INTEGER REFERENCES projects
(id)
);

INSERT INTO projects
    ( name, priority, description, deliverydate)
VALUES
    ('Make a web App', '1', 'Using Php', '2019-12-18');

INSERT INTO projects
    ( name, priority, description, deliverydate)
VALUES
    ('Make an App', '1', 'Using Java', '2019-12-18');

INSERT INTO projects
    ( name, priority, description, deliverydate)
VALUES
    ('Make an Desktop App', 2, 'Using Electron', '2019-12-18');



INSERT INTO tasks (name, done, projectid) VALUES ('dowload Php', false, 1);

INSERT INTO tasks (name, done, projectid) VALUES ('dowload Java', false, 2);

INSERT INTO tasks (name, done, projectid) VALUES ('dowload React Js', false, 3);
INSERT INTO tasks (name, done, projectid) VALUES ('Desing UI', false, 3);
